language: node_js
node_js:
- '16.16.0'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # Token to access Cozy Registry, you should replace it with a token specific to this konnector
  - secure: nrrnrwEFBslPPPh1Ljqlat1mpBWFcRErSPLzMeTi63pBMv1o2l/yyI4S9iHM1lf2QqoSHBZG7m93hEd4mHR7KMv/GDmWZjjgU5ieUs9O/JVm42ZJ0x9Ci5X5yEfM6lRi1SRiTVNvWpFBptYjM3yIoGHujyWpT8GDExgFhgSIe3k8dD/TcogJMIdL1JC+kWqSaXDawIarNtZc3hO4GvdvOy/bAjugJBHmhAmx00i9oIJYjxO9odet1B9Twv/2mxbzMAiKNUbOJxOrfOS6w+NHZ9SmrKtTFadxDlfUJm1F3W2tRy7OuXBkHLWZ0qdyu0BLkIlrXBqgfRgtsqfZneKiVSsxfdnewml4x5OY+L3ybVomfpcx43RCj4uRlGGmt5UCClGPVt/6PcNAoYlytSa0Qizci/zTPgB53IET/XKl+ipSkYiH+uHo4eiykQgtkppnBLLhR9GaP1nXHq5QCvMbVbb/iQ3y3Y2p1LDi+CR7OFNDCTEbOGVcPPJy6X7//17rGo7z4LPomikKK1gaX7hVejpVqbZNlwnym9u/0YpMLQiUGeeF8YOZHiqfCitA/AHjfDZFrbLKqiqey9uuZtdoII9DL/3++/akV458fugfHBuCYcy74JnUTzgTa52AQDAppZdtRXU/GLw/QxyxENbU3rqBtEKl6dke8bTABr3Rbqw=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
# run the yarn travisDeployKey command to generate this
# - openssl aes-256-cbc -K $encrypted_0b21ecdcf920_key -iv $encrypted_0b21ecdcf920_iv
#   -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
